package kr.or.ddit.study10;

import java.util.Scanner;

public class Exception2 {
	Scanner sc = new Scanner(System.in);

	public static void main(String[] args) {
		Exception2 obj = new Exception2();
		obj.process();

	}

	public void process() {
		method1();// method1()치고 f2누르면 create로 자동 생성됨 이걸 이제 알려주냠-_-
	}
	
	public void method1() {
		int[] arr = {1, 2, 0};
		System.out.println("배열 번호 입력");
		int num = sc.nextInt();
		// 파란줄에 뜬 부분을 try catch에 넣는다
		try {
			int result = 10/arr[num];
		} catch (Exception e) {
			System.out.println("배열 범위를 벗어남");
		}
		//java.lang.ArrayIndexOutOfBoundsException
		
		
	}

}
